version: '3'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.0
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mishutka2000
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_HOST: 192.168.99.100
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=3306
      - DBPASSWORD=Mishutka2000
      - ASPNETCORE_ENVIRONMENT=Development